<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run()
    {
        DB::table('menu')->insert([
            [
                'id_menu' => 1,
                'nama_menu' => 'Banana Ice Cream',
                'deskripsi_menu' => 'Delicious Banana Ice Cream made with fresh ingredients.',
                'harga' => 25000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/banana-ice-cream.PNG',
            ],
            [
                'id_menu' => 2,
                'nama_menu' => 'Bold Baileys',
                'deskripsi_menu' => 'A bold and creamy Baileys-inspired drink.',
                'harga' => 28000,
                'stok' => 15,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/bold-baileys.PNG',
            ],
            [
                'id_menu' => 3,
                'nama_menu' => 'Bold Seasalt Caramel',
                'deskripsi_menu' => 'Perfect blend of caramel and seasalt.',
                'harga' => 28000,
                'stok' => 15,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/bold-seasalt-caramel.PNG',
            ],
            [
                'id_menu' => 4,
                'nama_menu' => 'Caramel Macchiato',
                'deskripsi_menu' => 'Smooth espresso with caramel sweetness.',
                'harga' => 30000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/caramel-macchiato.PNG',
            ],
            [
                'id_menu' => 5,
                'nama_menu' => 'Cheese Toast And Fries',
                'deskripsi_menu' => 'Crispy fries and melted cheese on toast.',
                'harga' => 32000,
                'stok' => 25,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/cheese-toast-and-fries.PNG',
            ],
            [
                'id_menu' => 6,
                'nama_menu' => 'Cheezy Peazy Burger',
                'deskripsi_menu' => 'Juicy burger with extra cheese.',
                'harga' => 35000,
                'stok' => 20,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/cheezy-peazy-burger.PNG',
            ],
            [
                'id_menu' => 7,
                'nama_menu' => 'Chickin Cheetoz',
                'deskripsi_menu' => 'Crispy chicken coated with Cheetos flavor.',
                'harga' => 34000,
                'stok' => 25,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/chickin-cheetoz.PNG',
            ],
            [
                'id_menu' => 8,
                'nama_menu' => 'Coko',
                'deskripsi_menu' => 'Rich chocolate drink with creamy texture.',
                'harga' => 22000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/coko.PNG',
            ],
            [
                'id_menu' => 9,
                'nama_menu' => 'Crinkle Fries',
                'deskripsi_menu' => 'Crispy and salty crinkle-cut fries.',
                'harga' => 18000,
                'stok' => 40,
                'kategori' => 'Snack',
                'img_menu' => 'image/menu/crinkle-fries.PNG',
            ],
            [
                'id_menu' => 10,
                'nama_menu' => 'Curry Rice',
                'deskripsi_menu' => 'Savory Japanese-style curry rice.',
                'harga' => 35000,
                'stok' => 30,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/curry-rice.PNG',
            ],
            [
                'id_menu' => 11,
                'nama_menu' => 'Fresh Oren',
                'deskripsi_menu' => 'Fresh orange drink with natural flavor.',
                'harga' => 20000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/fresh-oren.PNG',
            ],
            [
                'id_menu' => 12,
                'nama_menu' => 'Gyuniku Rice',
                'deskripsi_menu' => 'Rice bowl with seasoned beef.',
                'harga' => 38000,
                'stok' => 25,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/gyuniku-rice.PNG',
            ],
            [
                'id_menu' => 13,
                'nama_menu' => 'Kafo',
                'deskripsi_menu' => 'Strong and bold brewed coffee.',
                'harga' => 22000,
                'stok' => 30,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/kafo.PNG',
            ],
            [
                'id_menu' => 14,
                'nama_menu' => 'Katsudon',
                'deskripsi_menu' => 'Crispy chicken katsu with rice.',
                'harga' => 40000,
                'stok' => 20,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/katsudon.PNG',
            ],
            [
                'id_menu' => 15,
                'nama_menu' => 'Matcha',
                'deskripsi_menu' => 'Premium Japanese matcha drink.',
                'harga' => 25000,
                'stok' => 25,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/matcha.PNG',
            ],
            [
                'id_menu' => 16,
                'nama_menu' => 'Milk Mango',
                'deskripsi_menu' => 'Fresh mango blended with creamy milk.',
                'harga' => 24000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/milk-mango.PNG',
            ],
            [
                'id_menu' => 17,
                'nama_menu' => 'Milk Milo',
                'deskripsi_menu' => 'Classic Milo drink served cold.',
                'harga' => 23000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/milk-milo.PNG',
            ],
            [
                'id_menu' => 18,
                'nama_menu' => 'Moko Minto',
                'deskripsi_menu' => 'Refreshing mint chocolate drink.',
                'harga' => 24000,
                'stok' => 25,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/moko-minto.PNG',
            ],
            [
                'id_menu' => 19,
                'nama_menu' => 'Nashville Chickin Nugget',
                'deskripsi_menu' => 'Spicy Nashville-style chicken nuggets.',
                'harga' => 33000,
                'stok' => 30,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/nashville-chickin-nugget.PNG',
            ],
            [
                'id_menu' => 20,
                'nama_menu' => 'Potato Wedge',
                'deskripsi_menu' => 'Thick-cut potato wedges with seasoning.',
                'harga' => 17000,
                'stok' => 35,
                'kategori' => 'Snack',
                'img_menu' => 'image/menu/potato-wedge.PNG',
            ],
            [
                'id_menu' => 21,
                'nama_menu' => 'Samosa Bolognese',
                'deskripsi_menu' => 'Crispy samosa filled with bolognese sauce.',
                'harga' => 22000,
                'stok' => 20,
                'kategori' => 'Food',
                'img_menu' => 'image/menu/samosa-bolognese.PNG',
            ],
            [
                'id_menu' => 22,
                'nama_menu' => 'Seasalt Caramel',
                'deskripsi_menu' => 'Sweet caramel drink balanced with seasalt.',
                'harga' => 26000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/seasalt-caramel.PNG',
            ],
            [
                'id_menu' => 23,
                'nama_menu' => 'Sunkistpresso',
                'deskripsi_menu' => 'Unique mix of sunkist and espresso.',
                'harga' => 28000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/sunkistpresso.PNG',
            ],
            [
                'id_menu' => 24,
                'nama_menu' => 'Tonic Oren',
                'deskripsi_menu' => 'Refreshing tonic with orange flavor.',
                'harga' => 21000,
                'stok' => 25,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/tonic-oren.PNG',
            ],
            [
                'id_menu' => 25,
                'nama_menu' => 'Yakult Lychee',
                'deskripsi_menu' => 'Yakult mixed with fresh lychee.',
                'harga' => 23000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/yakult-lychee.PNG',
            ],
            [
                'id_menu' => 26,
                'nama_menu' => 'Yakult Berry',
                'deskripsi_menu' => 'Yakult blended with berry flavor.',
                'harga' => 23000,
                'stok' => 20,
                'kategori' => 'Drink',
                'img_menu' => 'image/menu/yakult-berry.PNG',
            ],
        ]);
    }
}
